version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: posty_passy
      POSTGRES_USER: planner_db
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  planner:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
