version: "3.9"

services:
  db:
    container_name: planner_db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: posty_passy # Change this
      POSTGRES_USER: planner_db # Change this
      POSTGRES_DB: planner_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - planner_network

  planner_server:
    container_name: planner_server
    build: .
    restart: always
    ports:
      - "8080:8080"
    networks:
      - planner_network
    depends_on:
      - db
    environment:
      POSTGRES_PASSWORD: posty_passy # Change this
      POSTGRES_USER: planner_db # Change this
      POSTGRES_DB: planner_db
      DB_PORT: 5432
      DB_HOST: db
      JWT_SECRET: d7b31cf75011920a7b1fed033b93 # Change this to your JWT secret key

networks:
  planner_network:
    driver: bridge
