version: "3.9"

services:
  db:
    container_name: planner_db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: posty_passy
      POSTGRES_USER: planner_db
      POSTGRES_DB: planner_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - planner-network
    ports:
      - "5432:5432"

  planner:
    container_name: planner_server
    build: .
    restart: always
    ports:
      - "8085:8080"
    depends_on:
      - db
    environment:
      POSTGRES_PASSWORD: posty_passy
      POSTGRES_USER: planner_db
      POSTGRES_DB: planner_db
      DB_PORT: 5432
      DB_HOST: planner_db
      JWT_SECRET: d7b31cf75011920a7b1fed033b93f6be73fa2ddc1026f2ed2441b9c40b76ffc2685ec76e7f52e3a6c4e239371047f16bd9b88fadba2681268e1608bde15f7907 #Change this to your JWT secret key
    networks:
      - planner-network

networks:
  planner-network:
    driver: bridge
